// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjtkoroekjwbjiakcxqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqdGtvcm9la2p3YmppYWtjeHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDI4MzUsImV4cCI6MjA2OTk3ODgzNX0.vCJG4blLx17Px2JqSCPGxKOjhvijPC4pSxZ1vNA-N-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});